#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running Prettier (format)..."
npm run format

echo "Checking Code Style with Prettier..."
npm run check-format

echo "Running ESLint (lint)..."
npm run lint

echo "Running Tests..."
npm test